import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Clock3, ShieldCheck, ShoppingBag, Sparkles, Truck, Zap } from 'lucide-react';
import { useStore } from '../context/StoreContext';
import { CATEGORIES } from '../data/categories';
import { formatPrice } from '../utils/formatters';
import { Product } from '../types';
import { CartDrawer } from './CartDrawer';
import { CheckoutModal } from './CheckoutModal';
import { Toast } from './Toast';
import { Footer } from './Footer';

function untilMidnight(){const now=new Date(),end=new Date(now);end.setHours(24,0,0,0);return Math.max(0,Math.floor((end.getTime()-now.getTime())/1000))}
function Timer(){const [seconds,setSeconds]=useState(untilMidnight);useEffect(()=>{const timer=setInterval(()=>setSeconds(untilMidnight()),1000);return()=>clearInterval(timer)},[]);const values=[Math.floor(seconds/3600),Math.floor(seconds%3600/60),seconds%60];return <div className="flex items-center gap-2">{values.map((value,index)=><React.Fragment key={index}>{index>0&&<b className="text-orange-300">:</b>}<div className="rounded-xl bg-white/10 border border-white/15 min-w-16 p-2 text-center"><div className="text-2xl font-black tabular-nums">{String(value).padStart(2,'0')}</div><div className="text-[9px] uppercase tracking-widest text-neutral-400">{['Hours','Mins','Secs'][index]}</div></div></React.Fragment>)}</div>}

function CollectionCard({product}:{product:Product}){const {currency,rateSSP,addToCart,setIsCartOpen}=useStore();const save=Math.max(0,product.originalPriceUSD-product.priceUSD);return <article className="group bg-white rounded-3xl border border-neutral-200 overflow-hidden hover:shadow-xl transition"><a href={`/product/${product.slug}`} className="block relative aspect-[4/3] overflow-hidden bg-neutral-100"><img src={product.images[0]} alt={product.title} className="w-full h-full object-cover group-hover:scale-105 transition duration-500"/><span className="absolute top-3 left-3 rounded-full bg-neutral-950 text-yellow-300 px-3 py-1 text-[10px] font-black">{save>0?`SAVE $${save}`:'DAILY OFFER'}</span></a><div className="p-5"><div className="text-[10px] uppercase tracking-widest text-orange-600 font-black">{product.subCategory||product.category}</div><a href={`/product/${product.slug}`}><h3 className="font-black mt-2 line-clamp-2 min-h-12">{product.title}</h3></a><div className="flex items-end gap-2 mt-3"><b className="text-xl">{formatPrice(product.priceUSD,currency,rateSSP)}</b>{save>0&&<span className="text-sm text-neutral-400 line-through">{formatPrice(product.originalPriceUSD,currency,rateSSP)}</span>}</div><div className="flex gap-2 mt-4"><a href={`/product/${product.slug}`} className="flex-1 rounded-xl border border-neutral-300 py-2.5 text-center text-xs font-black">View Offer</a><button onClick={()=>{addToCart(product);setIsCartOpen(true)}} className="rounded-xl bg-orange-600 text-white px-4"><ShoppingBag className="w-4 h-4"/></button></div></div></article>}

export const CollectionLandingPage=({slug}:{slug:string})=>{const {products}=useStore();const category=CATEGORIES.find(item=>item.slug===slug&&item.slug!=='all');const items=useMemo(()=>products.filter(item=>item.category===slug),[products,slug]);const featured=items.find(item=>item.isFeatured)||items[0];const recommendations=useMemo(()=>items.filter(item=>item.id!==featured?.id).sort((a,b)=>(b.isBestSeller?1:0)-(a.isBestSeller?1:0)||b.rating-a.rating).slice(0,4),[items,featured]);const related=useMemo(()=>products.filter(item=>item.category!==slug).slice(0,4),[products,slug]);useEffect(()=>{document.title=category?`${category.name} Collection | Infinite Mart Juba`:'Collection | Infinite Mart';window.scrollTo(0,0)},[category]);if(!category||!featured)return <main className="min-h-screen bg-neutral-950 text-white grid place-items-center text-center"><div><h1 className="text-3xl font-black">Collection not found</h1><a href="/" className="inline-block mt-5 rounded-xl bg-orange-600 px-5 py-3 font-black">Back to store</a></div></main>;
return <div className="min-h-screen bg-[#f7f7f5] text-neutral-950"><div className="bg-black text-white text-center text-xs font-bold py-2">Free Juba delivery on selected collection orders · Today only</div><header className="bg-white border-b sticky top-0 z-30"><div className="max-w-7xl mx-auto h-16 px-4 flex items-center justify-between"><a href="/" className="font-black text-xl">Infinite<span className="text-orange-600">Mart</span></a><a href="/" className="flex items-center gap-2 text-xs font-bold"><ArrowLeft className="w-4 h-4"/> All collections</a></div></header>
<main><section className="relative overflow-hidden bg-neutral-950 text-white"><div className="absolute inset-0"><img src={category.image} alt="" className="w-full h-full object-cover opacity-25"/><div className="absolute inset-0 bg-gradient-to-r from-black via-black/85 to-black/20"/></div><div className="relative max-w-7xl mx-auto px-4 py-16 lg:py-24 grid lg:grid-cols-2 gap-12 items-center"><div><span className="inline-flex items-center gap-2 text-orange-300 text-xs font-black uppercase tracking-[.2em]"><Sparkles className="w-4 h-4"/> {category.subtitle}</span><h1 className="text-5xl lg:text-7xl font-black tracking-[-.05em] leading-none mt-4">{category.name}<br/>Collection</h1><p className="text-neutral-300 mt-5 max-w-xl">Discover {items.length} carefully selected products with authentic quality, local support and fast delivery throughout Juba.</p><a href="#collection-products" className="inline-flex items-center gap-2 bg-orange-600 rounded-xl px-6 py-3 font-black mt-7">Shop this collection <ArrowRight className="w-4 h-4"/></a></div><div className="rounded-3xl bg-white/10 backdrop-blur border border-white/15 p-6"><div className="flex items-center gap-2 text-orange-300 text-xs font-black uppercase tracking-widest"><Clock3 className="w-4 h-4"/> Collection offer ends in</div><Timer/><div className="grid grid-cols-3 gap-2 mt-5 text-center text-[10px]"><div className="rounded-xl bg-white/5 p-3"><Truck className="w-5 h-5 mx-auto mb-1"/>Fast delivery</div><div className="rounded-xl bg-white/5 p-3"><ShieldCheck className="w-5 h-5 mx-auto mb-1"/>Authentic stock</div><div className="rounded-xl bg-white/5 p-3"><Zap className="w-5 h-5 mx-auto mb-1"/>Daily prices</div></div></div></div></section>
<section className="max-w-7xl mx-auto px-4 py-12"><div className="grid lg:grid-cols-2 gap-6 bg-white rounded-[2rem] p-5 lg:p-8 border"><a href={`/product/${featured.slug}`} className="rounded-3xl overflow-hidden aspect-[4/3]"><img src={featured.images[0]} alt={featured.title} className="w-full h-full object-cover"/></a><div className="flex flex-col justify-center"><span className="text-orange-600 text-xs font-black uppercase tracking-[.2em]">Offer of the day</span><h2 className="text-3xl lg:text-4xl font-black mt-3">{featured.title}</h2><p className="text-neutral-500 mt-4 line-clamp-3">{featured.description}</p><div className="flex gap-3 items-end mt-5"><b className="text-3xl">${featured.priceUSD}</b><span className="line-through text-neutral-400">${featured.originalPriceUSD}</span></div><a href={`/product/${featured.slug}`} className="inline-flex self-start mt-6 bg-neutral-950 text-yellow-300 rounded-xl px-6 py-3 font-black">Claim today’s offer</a></div></div></section>
<section className="max-w-7xl mx-auto px-4 py-8" id="collection-products"><span className="text-orange-600 text-xs font-black uppercase tracking-[.2em]">Shop all</span><h2 className="text-3xl font-black mt-2">{category.name} deals</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5 mt-7">{items.map(item=><React.Fragment key={item.id}><CollectionCard product={item}/></React.Fragment>)}</div></section>
{recommendations.length>0&&<section className="bg-white py-14 mt-10"><div className="max-w-7xl mx-auto px-4"><span className="text-orange-600 text-xs font-black uppercase tracking-[.2em]">Recommended</span><h2 className="text-3xl font-black mt-2">Popular in this collection</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5 mt-7">{recommendations.map(item=><React.Fragment key={item.id}><CollectionCard product={item}/></React.Fragment>)}</div></div></section>}
{related.length>0&&<section className="max-w-7xl mx-auto px-4 py-14"><h2 className="text-2xl font-black">You may also like</h2><div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mt-6">{related.map(item=><a key={item.id} href={`/product/${item.slug}`} className="rounded-2xl bg-white border p-3"><img src={item.images[0]} alt={item.title} className="rounded-xl aspect-[4/3] w-full object-cover"/><h3 className="font-black text-sm mt-3 line-clamp-2">{item.title}</h3><b className="text-sm mt-1 block">${item.priceUSD}</b></a>)}</div></section>}
</main><Footer/><CartDrawer/><CheckoutModal/><Toast/></div>}
