import React, { useEffect, useMemo, useState } from 'react';
import { ArrowRight, ChevronDown, Headphones, Heart, LockKeyhole, Menu, RefreshCw, Search, ShieldCheck, ShoppingBag, Truck, UserRound, X, Zap } from 'lucide-react';
import { useStore } from '../context/StoreContext';
import { CATEGORIES } from '../data/categories';
import { formatPrice } from '../utils/formatters';
import { Product } from '../types';

const navItems=['Home','Shop','New Arrivals','Best Sellers','Categories','About','Contact'];

function DealTimer(){const calc=()=>{const n=new Date(),e=new Date(n);e.setHours(24,0,0,0);return Math.floor((e.getTime()-n.getTime())/1000)};const [s,setS]=useState(calc);useEffect(()=>{const t=setInterval(()=>setS(calc()),1000);return()=>clearInterval(t)},[]);return <div className="flex gap-3 mt-5">{[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map((v,i)=><div key={i}><b className="text-2xl tabular-nums">{String(v).padStart(2,'0')}</b><span className="block text-[9px] uppercase opacity-70">{['Hours','Mins','Secs'][i]}</span></div>)}</div>}

function MiniProduct({product}:{product:Product}){const {currency,rateSSP,addToCart,toggleWishlist,isInWishlist,setIsCartOpen}=useStore();return <article className="group min-w-0"><div className="relative bg-[#f3f3f1] rounded-2xl overflow-hidden aspect-[4/5]"><a href={`/products/${product.slug}`}><img src={product.images[0]} alt={product.title} className="w-full h-full object-cover transition duration-500 group-hover:scale-105"/></a><span className="absolute top-3 left-3 rounded-full bg-neutral-950 text-white px-2.5 py-1 text-[9px] font-black">{product.discountBadge?'SALE':'NEW'}</span><button onClick={()=>toggleWishlist(product.id)} className="absolute top-3 right-3 rounded-full bg-white w-8 h-8 grid place-items-center shadow-sm"><Heart className={`w-4 h-4 ${isInWishlist(product.id)?'fill-red-500 text-red-500':''}`}/></button><button onClick={()=>{addToCart(product);setIsCartOpen(true)}} className="absolute right-3 bottom-3 rounded-full bg-neutral-950 text-white w-9 h-9 grid place-items-center"><ShoppingBag className="w-4 h-4"/></button></div><a href={`/products/${product.slug}`} className="block mt-3"><h3 className="font-bold text-sm line-clamp-1">{product.title}</h3><div className="flex gap-2 items-center mt-1"><b className="text-sm">{formatPrice(product.priceUSD,currency,rateSSP)}</b>{product.originalPriceUSD>product.priceUSD&&<span className="text-xs text-neutral-400 line-through">${product.originalPriceUSD}</span>}</div><div className="text-[10px] mt-1 text-amber-500">★★★★★ <span className="text-neutral-400">({product.reviewCount})</span></div></a></article>}

export const ModernStorefront=()=>{const {products,cartCount,setIsCartOpen,setIsWishlistOpen,setSearchQuery,setActiveCategory}=useStore();const [mobile,setMobile]=useState(false),[search,setSearch]=useState(false),[query,setQuery]=useState('');const featured=products.find(p=>p.id==='prod-s25-ultra')||products[0];const arrivals=products.slice(0,6);const best=useMemo(()=>products.filter(p=>p.isBestSeller).slice(0,3),[products]);const go=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});const submit=(e:React.FormEvent)=>{e.preventDefault();setSearchQuery(query);setActiveCategory('all');setSearch(false);go('products-section')};return <div className="bg-white text-neutral-950">
 <div className="bg-black text-white text-[10px] sm:text-xs"><div className="max-w-7xl mx-auto px-4 py-2 flex justify-center sm:justify-between"><span>🚚 Free Juba delivery over $100</span><span className="hidden sm:block">⚡ Same-day flash deals</span><span className="hidden sm:block">✓ 100% genuine products</span></div></div>
 <header className="sticky top-0 z-40 bg-white/95 backdrop-blur border-b border-neutral-100"><div className="max-w-7xl mx-auto h-16 px-4 flex items-center justify-between"><button className="lg:hidden" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><a href="/" className="text-xl font-black tracking-tight">Infinite<span className="text-orange-600">Mart</span></a><nav className="hidden lg:flex items-center gap-7">{navItems.map((n,i)=><button key={n} onClick={()=>go(i===0?'top':i===2?'new':i===3?'best':'shop')} className={`text-xs font-semibold hover:text-orange-600 ${i===0?'text-orange-600':''}`}>{n}{n==='Categories'&&<ChevronDown className="inline w-3 h-3 ml-1"/>}</button>)}</nav><div className="flex items-center gap-4"><button onClick={()=>setSearch(true)}><Search className="w-5 h-5"/></button><button className="hidden sm:block" onClick={()=>setIsWishlistOpen(true)}><Heart className="w-5 h-5"/></button><UserRound className="hidden sm:block w-5 h-5"/><button onClick={()=>setIsCartOpen(true)} className="relative"><ShoppingBag className="w-5 h-5"/>{cartCount>0&&<span className="absolute -top-2 -right-2 bg-orange-600 text-white rounded-full text-[9px] w-4 h-4 grid place-items-center">{cartCount}</span>}</button></div></div>{mobile&&<div className="lg:hidden px-4 pb-4 grid gap-2">{navItems.map(n=><button key={n} onClick={()=>{go(n==='New Arrivals'?'new':n==='Best Sellers'?'best':'shop');setMobile(false)}} className="text-left py-2 text-sm font-semibold">{n}</button>)}</div>}</header>
 {search&&<div className="fixed inset-0 z-50 bg-black/50 p-4 grid place-items-start pt-24"><form onSubmit={submit} className="bg-white w-full max-w-2xl rounded-2xl p-3 flex gap-2"><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Infinite Mart..." className="flex-1 px-3 outline-none"/><button className="bg-black text-white rounded-xl px-5 font-bold">Search</button><button type="button" onClick={()=>setSearch(false)}><X/></button></form></div>}
 <main id="top">
  <section className="relative overflow-hidden bg-[#f4f4f2]"><div className="max-w-7xl mx-auto min-h-[560px] lg:min-h-[610px] px-4 grid lg:grid-cols-2 items-center"><div className="z-10 py-14"><span className="text-orange-600 text-xs font-black uppercase tracking-[.2em]">Trending in Juba</span><h1 className="text-5xl sm:text-6xl lg:text-7xl font-black tracking-[-.05em] leading-[.95] mt-4">Discover products<br/>you’ll love</h1><p className="text-neutral-500 max-w-md mt-6 leading-relaxed">Shop original electronics, Arabian fragrances, skincare and modern home essentials—curated for life in Juba.</p><div className="flex flex-wrap gap-3 mt-8"><button onClick={()=>go('new')} className="bg-orange-600 text-white rounded-lg px-6 py-3 text-sm font-bold flex gap-2 items-center">Shop Now <ArrowRight className="w-4 h-4"/></button><button onClick={()=>go('shop')} className="bg-white border rounded-lg px-6 py-3 text-sm font-bold">Explore Collection</button></div><div className="flex items-center gap-3 mt-10"><div className="flex -space-x-2">{products.slice(0,4).map(p=><img key={p.id} src={p.images[0]} className="w-8 h-8 rounded-full object-cover border-2 border-white"/>)}</div><span className="text-xs text-neutral-500">Loved by shoppers across Juba</span></div></div><div className="relative h-[430px] lg:h-full"><div className="absolute inset-x-8 bottom-0 top-8 bg-gradient-to-br from-orange-500 to-red-500 rounded-[50%_50%_15%_15%] rotate-[-8deg]"/><img src={featured.images[0]} alt={featured.title} className="absolute inset-0 w-full h-full object-contain drop-shadow-2xl z-10 p-10"/><a href={`/products/${featured.slug}`} className="absolute z-20 top-14 right-0 bg-white rounded-xl p-3 shadow-xl w-36"><span className="text-[9px] text-neutral-500">Offer of the day</span><b className="block text-xs line-clamp-2">{featured.title}</b><strong className="text-xs">${featured.priceUSD}</strong></a><a href={`/products/${products[4]?.slug}`} className="absolute z-20 bottom-20 left-0 bg-white rounded-xl p-3 shadow-xl w-36"><span className="text-[9px] text-neutral-500">Popular pick</span><b className="block text-xs line-clamp-2">{products[4]?.title}</b><strong className="text-xs">${products[4]?.priceUSD}</strong></a></div></div></section>
  <section className="border-y"><div className="max-w-7xl mx-auto px-4 py-6 grid grid-cols-2 lg:grid-cols-4 gap-6">{[[Truck,'Free Shipping','Orders over $100'],[LockKeyhole,'Secure Payments','Protected checkout'],[RefreshCw,'Easy Returns','Simple return policy'],[Headphones,'Juba Support','We are here to help']].map(([Icon,t,s]:any)=><div key={t} className="flex items-center gap-3"><Icon className="w-6 h-6"/><div><b className="block text-xs">{t}</b><span className="text-[10px] text-neutral-400">{s}</span></div></div>)}</div></section>
  <section id="shop" className="max-w-7xl mx-auto px-4 py-12"><div className="flex justify-between items-end"><div><span className="text-[10px] uppercase text-orange-600 font-black tracking-widest">Explore departments</span><h2 className="text-2xl font-black mt-1">Shop by Categories</h2></div><button onClick={()=>{setActiveCategory('all');go('products-section')}} className="text-xs font-bold">View All Categories →</button></div><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3 mt-6">{CATEGORIES.filter(c=>c.id!=='all').slice(0,6).map(c=><button key={c.id} onClick={()=>{setSearchQuery('');setActiveCategory(c.slug);go('products-section')}} className="relative rounded-2xl overflow-hidden aspect-[4/3] text-left group"><img src={c.image} alt={c.name} className="w-full h-full object-cover group-hover:scale-105 transition"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent"/><div className="absolute bottom-3 left-3 text-white"><b className="block text-sm">{c.name}</b><span className="text-[10px]">Shop Now →</span></div></button>)}</div></section>
  <section id="new" className="max-w-7xl mx-auto px-4 pb-14"><div className="flex justify-between"><h2 className="text-2xl font-black">New Arrivals</h2><a href="#shop" className="text-xs font-bold">View All New Arrivals →</a></div><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mt-6">{arrivals.map(p=><React.Fragment key={p.id}><MiniProduct product={p}/></React.Fragment>)}</div></section>
  <section id="best" className="bg-[#fafaf8] py-14"><div className="max-w-7xl mx-auto px-4"><div className="flex justify-between"><h2 className="text-2xl font-black">Best Sellers</h2><a href="#shop" className="text-xs font-bold">View All Best Sellers →</a></div><div className="grid md:grid-cols-3 gap-4 mt-6">{best.map(p=><article key={p.id} className="bg-white rounded-2xl p-4 flex items-center gap-4"><img src={p.images[0]} className="w-32 h-36 object-cover rounded-xl"/><div><span className="rounded-full bg-amber-200 px-2 py-1 text-[9px] font-black">Bestseller</span><h3 className="font-black mt-3 line-clamp-2">{p.title}</h3><b className="block mt-2">${p.priceUSD}</b><a href={`/products/${p.slug}`} className="inline-block bg-black text-white rounded-lg px-4 py-2 text-xs font-bold mt-4">Quick View</a></div></article>)}</div></div></section>
  <section className="max-w-7xl mx-auto px-4 py-12 grid lg:grid-cols-2 gap-4"><div className="relative overflow-hidden rounded-3xl bg-gradient-to-r from-orange-600 to-red-400 text-white p-8 min-h-64"><span className="text-xs">Flash Sale</span><h2 className="text-3xl font-black mt-1">Up To 40% Off</h2><DealTimer/><button onClick={()=>go('new')} className="mt-6 bg-white text-black rounded-lg px-4 py-2 text-xs font-black">Shop Sale Now</button><Zap className="absolute right-8 bottom-5 w-40 h-40 opacity-20"/></div><div className="relative overflow-hidden rounded-3xl bg-neutral-950 text-white p-8 min-h-64"><span className="text-xs">New Collection</span><h2 className="text-3xl font-black mt-1">Everyday Essentials</h2><p className="text-sm text-neutral-400 mt-3 max-w-xs">Upgrade your routine with genuine tech, fragrance and smart-living picks.</p><button onClick={()=>go('shop')} className="mt-6 bg-white text-black rounded-lg px-4 py-2 text-xs font-black">Shop Collection</button><ShieldCheck className="absolute right-8 bottom-5 w-40 h-40 text-orange-500 opacity-30"/></div></section>
  <section className="bg-[#fafaf8] border-t"><div className="max-w-7xl mx-auto px-4 py-7 grid grid-cols-2 lg:grid-cols-4 gap-6">{[[ShieldCheck,'Premium Quality'],[Truck,'Fast Delivery'],[LockKeyhole,'Secure Checkout'],[Heart,'Customer Satisfaction']].map(([Icon,t]:any)=><div key={t} className="flex justify-center items-center gap-3 text-xs font-bold"><Icon className="w-5 h-5"/>{t}</div>)}</div></section>
 </main></div>}
