import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, Clock3, Minus, Plus, ShieldCheck, ShoppingBag, Star, Truck, Zap } from 'lucide-react';
import { useStore } from '../context/StoreContext';
import { formatPrice } from '../utils/formatters';

const leftToday = () => { const n=new Date(), m=new Date(n); m.setHours(24,0,0,0); return Math.max(0,Math.floor((m.getTime()-n.getTime())/1000)); };
function Countdown(){const [s,setS]=useState(leftToday);useEffect(()=>{const t=setInterval(()=>setS(leftToday()),1000);return()=>clearInterval(t)},[]);const parts=[Math.floor(s/3600),Math.floor(s%3600/60),s%60];return <div className="flex items-center gap-2">{parts.map((v,i)=><React.Fragment key={i}>{i>0&&<b className="text-yellow-300">:</b>}<div className="min-w-14 rounded-xl bg-white/10 border border-white/15 p-2 text-center"><div className="text-xl font-black tabular-nums">{String(v).padStart(2,'0')}</div><div className="text-[9px] uppercase text-neutral-400">{['Hours','Mins','Secs'][i]}</div></div></React.Fragment>)}</div>}

export const ProductLandingPage=({slug}:{slug:string})=>{
 const {products,currency,rateSSP,addToCart,setIsCartOpen,showToast}=useStore();
 const product=products.find(p=>p.slug===slug); const [image,setImage]=useState(0),[qty,setQty]=useState(1),[options,setOptions]=useState<string[]>([]),[bundle,setBundle]=useState<string[]>([]);
 const recs=useMemo(()=>{
  if(!product)return [];
  const pairs:Record<string,string[]>={smartphones:['charging','audio','smartwatches'],laptops:['charging','audio','home'],gaming:['audio','charging','smartphones'],perfumes:['skincare','perfumes'],skincare:['perfumes','skincare'],audio:['smartphones','laptops','charging'],smartwatches:['charging','smartphones','audio'],home:['charging','home'],charging:['smartphones','laptops','smartwatches']};
  const preferred=pairs[product.category]||[];
  return products.filter(p=>p.id!==product.id).sort((a,b)=>{const ai=preferred.indexOf(a.category),bi=preferred.indexOf(b.category);return (ai<0?99:ai)-(bi<0?99:bi)}).slice(0,3);
 },[product,products]);
 useEffect(()=>{if(!product)return;setOptions(product.variants?.map(v=>v.options[0])||[]);setBundle(recs.slice(0,2).map(p=>p.id));document.title=`${product.title} | Infinite Mart Juba`;window.scrollTo(0,0)},[product,recs]);
 if(!product)return <main className="min-h-screen bg-neutral-950 text-white grid place-items-center text-center"><div><h1 className="text-3xl font-black">Product not found</h1><a href="/" className="inline-block mt-5 bg-yellow-400 text-black rounded-xl px-5 py-3 font-black">Back to store</a></div></main>;
 const saving=Math.max(0,product.originalPriceUSD-product.priceUSD), discount=Math.round(saving/product.originalPriceUSD*100), selected=recs.filter(p=>bundle.includes(p.id)), subtotal=product.priceUSD+selected.reduce((s,p)=>s+p.priceUSD,0), bundleSaving=selected.length?Math.min(35,Math.round(subtotal*.05)):0;
 const addMain=(open=true)=>{addToCart(product,qty,options[0],options[1]);if(open)setIsCartOpen(true)}; const addAll=()=>{addMain(false);selected.forEach(p=>addToCart(p));showToast(`Bundle added — save $${bundleSaving}!`,'success');setIsCartOpen(true)};
 return <div className="min-h-screen bg-[#f7f7f5] text-neutral-950">
  <div className="bg-neutral-950 text-white"><div className="max-w-7xl mx-auto px-4 py-2.5 flex justify-center gap-2 text-xs font-bold"><Zap className="w-4 h-4 text-yellow-300 fill-yellow-300"/> Offer of the day: save {discount}% with same-day Juba delivery</div></div>
  <header className="bg-white border-b sticky top-0 z-30"><div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between"><a href="/" className="flex items-center gap-2 font-black"><span className="grid place-items-center w-9 h-9 rounded-xl bg-yellow-400">⚡</span>INFINITE MART</a><a href="/" className="flex items-center gap-2 text-xs font-bold text-neutral-600"><ArrowLeft className="w-4 h-4"/> Back to store</a></div></header>
  <main><section className="max-w-7xl mx-auto px-4 py-8 lg:py-12 grid lg:grid-cols-2 gap-8 lg:gap-14">
   <div className="space-y-3"><div className="relative aspect-square rounded-[2rem] overflow-hidden bg-white border shadow-sm"><img src={product.images[image]||product.images[0]} alt={product.title} className="w-full h-full object-cover"/><div className="absolute top-4 left-4 flex flex-col gap-2"><span className="rounded-lg bg-black text-yellow-300 px-3 py-1.5 text-xs font-black uppercase">Offer of the day</span>{saving>0&&<span className="rounded-lg bg-yellow-400 px-3 py-1.5 text-xs font-black">SAVE ${saving}</span>}</div></div>{product.images.length>1&&<div className="grid grid-cols-3 gap-3">{product.images.slice(0,3).map((img,i)=><button key={img} onClick={()=>setImage(i)} className={`aspect-[4/3] rounded-2xl overflow-hidden border-2 ${image===i?'border-yellow-400':'border-transparent'}`}><img src={img} alt="" className="w-full h-full object-cover"/></button>)}</div>}</div>
   <div className="flex flex-col justify-center"><div className="text-xs font-black uppercase tracking-[.18em] text-amber-700">{product.subCategory||product.category}</div><h1 className="text-3xl sm:text-5xl font-black tracking-tight leading-[1.05] mt-3">{product.title}</h1><div className="flex items-center gap-2 mt-4 text-sm"><div className="flex">{[0,1,2,3,4].map(i=><Star key={i} className="w-4 h-4 fill-amber-400 text-amber-400"/>)}</div><b>{product.rating}</b><span className="text-neutral-500">({product.reviewCount} verified reviews)</span></div>
   <div className="mt-6 flex items-end gap-3 flex-wrap"><b className="text-4xl">{formatPrice(product.priceUSD,currency,rateSSP)}</b>{saving>0&&<><span className="text-lg text-neutral-400 line-through">{formatPrice(product.originalPriceUSD,currency,rateSSP)}</span><span className="rounded-full bg-emerald-100 text-emerald-800 px-3 py-1 text-xs font-black">-{discount}%</span></>}</div><p className="mt-5 text-neutral-600 leading-relaxed">{product.description}</p>
   <div className="mt-6 rounded-2xl bg-neutral-950 text-white p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-yellow-300 text-xs font-black uppercase tracking-widest"><Clock3 className="w-4 h-4"/> Today's deal ends in</div><p className="text-xs text-neutral-400 mt-1">Price resets at midnight</p></div><Countdown/></div>
   {product.variants?.map((v,vi)=><div key={v.name} className="mt-5"><div className="text-xs font-black uppercase mb-2">Choose {v.name}</div><div className="flex flex-wrap gap-2">{v.options.map(o=><button key={o} onClick={()=>setOptions(a=>a.map((x,i)=>i===vi?o:x))} className={`rounded-xl border px-4 py-2 text-xs font-bold ${options[vi]===o?'bg-black text-white':'bg-white'}`}>{o}</button>)}</div></div>)}
   <div className="mt-6 flex gap-3"><div className="flex items-center rounded-xl border bg-white"><button onClick={()=>setQty(Math.max(1,qty-1))} className="p-3"><Minus className="w-4 h-4"/></button><b className="w-8 text-center">{qty}</b><button onClick={()=>setQty(Math.min(product.stockCount,qty+1))} className="p-3"><Plus className="w-4 h-4"/></button></div><button onClick={()=>addMain()} className="flex-1 rounded-xl bg-yellow-400 px-5 py-3 font-black flex justify-center gap-2"><ShoppingBag className="w-5 h-5"/> Add to cart</button></div>
   <div className="grid grid-cols-3 gap-2 mt-4 text-[10px] sm:text-xs font-bold text-center"><div className="rounded-xl bg-white border p-3"><Truck className="w-5 h-5 mx-auto mb-1 text-amber-600"/>Same-day delivery</div><div className="rounded-xl bg-white border p-3"><ShieldCheck className="w-5 h-5 mx-auto mb-1 text-emerald-600"/>Local warranty</div><div className="rounded-xl bg-white border p-3"><Check className="w-5 h-5 mx-auto mb-1 text-blue-600"/>100% genuine</div></div></div>
  </section>
  <section className="bg-neutral-950 text-white py-14"><div className="max-w-7xl mx-auto px-4 grid lg:grid-cols-2 gap-10"><div><span className="text-yellow-300 text-xs font-black uppercase tracking-[.2em]">Why you'll love it</span><h2 className="text-3xl font-black mt-2">Built to impress. Backed locally.</h2><div className="grid sm:grid-cols-2 gap-3 mt-6">{product.features.map(f=><div key={f} className="rounded-2xl bg-white/5 border border-white/10 p-4 flex gap-3 text-sm"><Check className="w-5 h-5 text-yellow-300 shrink-0"/>{f}</div>)}</div></div><div className="rounded-3xl bg-white text-black p-6"><h3 className="text-xl font-black">Product specifications</h3><div className="mt-4 divide-y">{product.specs.map(s=><div key={s.label} className="py-3 flex justify-between gap-5 text-sm"><span className="text-neutral-500">{s.label}</span><b className="text-right">{s.value}</b></div>)}</div></div></div></section>
  {recs.length>0&&<section className="max-w-7xl mx-auto px-4 py-14"><span className="text-xs font-black uppercase tracking-[.2em] text-amber-700">Frequently bought together</span><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><h2 className="text-3xl font-black mt-2">Complete your setup</h2><p className="text-sm text-neutral-500">Select extras and add the bundle in one tap.</p></div><div><span className="text-neutral-500 text-sm">Bundle total </span><b className="text-xl">{formatPrice(subtotal-bundleSaving,currency,rateSSP)}</b>{bundleSaving>0&&<span className="ml-2 text-emerald-700 font-black">Save ${bundleSaving}</span>}</div></div><div className="grid md:grid-cols-3 gap-4 mt-7">{recs.map(p=>{const on=bundle.includes(p.id);return <button key={p.id} onClick={()=>setBundle(a=>on?a.filter(id=>id!==p.id):[...a,p.id])} className={`text-left rounded-3xl bg-white border-2 p-3 ${on?'border-yellow-400 shadow-lg':'border-neutral-200'}`}><div className="aspect-[4/3] rounded-2xl overflow-hidden relative"><img src={p.images[0]} alt={p.title} className="w-full h-full object-cover"/><span className={`absolute top-3 right-3 w-7 h-7 rounded-full grid place-items-center ${on?'bg-yellow-400':'bg-white text-transparent'}`}><Check className="w-4 h-4"/></span></div><div className="p-2"><h3 className="font-black text-sm line-clamp-2">{p.title}</h3><b className="block mt-2">+ {formatPrice(p.priceUSD,currency,rateSSP)}</b></div></button>})}</div><button onClick={addAll} className="mt-6 rounded-xl bg-neutral-950 text-yellow-300 px-7 py-4 font-black">Add selected bundle to cart</button></section>}</main>
  <footer className="bg-black text-neutral-400 text-xs py-8 text-center">© Infinite Mart Juba · Genuine products · Local warranty · Express delivery</footer>
 </div>
}
